---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: xyz-webapp
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/xyz-webapp
  prune: true
  sourceRef:
    kind: GitRepository
    name: aks-flux-extension
  validation: client

