---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: xyz-webapp
  namespace: flux-system
spec:
  interval: 2m0s
  url: oci://ghcr.io/sighup
  type: "oci"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: xyz-webapp
  namespace: flux-system
spec:
  interval: 2m
  targetNamespace: default
  chart:
    spec:
      chart: xyz-webapp
      version: '0.0.x'
      reconcileStrategy: Revision
      sourceRef:
        kind: HelmRepository
        name: xyz-webapp
        namespace: flux-system
      interval: 1m
  values:
    nodeSelector:
      kubernetes.io/os: linux
    ingress:
      enabled: true
      hosts:
        - host: xyz.local
          paths:
            - path: /
              pathType: ImplementationSpecific
